// Generates TypeScript declarations for the generated embind surface.

const SKIPPED_TYPES = [
  'std::shared_ptr',
  'std::vector',
  'FGTemplateFunc',
  'PropertyCatalogStructure',
  'Element',
  '*',
  'auto',
];

const INTERNAL_ONLY = new Set([
  'BuildPropertyCatalog',
  'GetTemplateFunc',
  'AddTemplateFunc',
  'GetRandomGenerator',
  'SRand',
  'Initialize',
]);

/**
 * @param {{name:string, returnType:string, params:{name:string,type:string}[]}[]} methods
 * @returns {string}
 */
export function renderTsApi(methods) {
  const declarations = methods
    .filter(isRepresentable)
    .filter(method => method.name !== 'QueryPropertyCatalog' || method.params.length === 2)
    .filter(method => method.name !== 'LoadModel' || isLoadModelStringOverload(method))
    .map(renderMethod)
    .filter(Boolean);

  const unique = [...new Map(declarations.map(line => [line, line])).values()];

  return `// Auto-generated by scripts/bindings-generator.
// Do not edit manually.

export interface FGFDMExecApi {
${unique.map(line => `  ${line}`).join('\n')}
  delete(): void;
}
`;
}

function renderMethod(method) {
  if (method.name === 'QueryPropertyCatalog') {
    return 'QueryPropertyCatalog(check: string): string;';
  }
  if (method.name === 'ResetToInitialConditions') {
    return 'ResetToInitialConditions(): void;';
  }

  const params = method.params.map(param => `${safeParamName(param.name)}: ${cppTypeToTs(param.type)}`).join(', ');
  return `${method.name}(${params}): ${cppTypeToTs(method.returnType)};`;
}

function isRepresentable(method) {
  if (INTERNAL_ONLY.has(method.name)) return false;
  if (method.isPureVirtual) return false;
  if (!isRepresentableType(method.returnType, { returnType: true })) return false;
  return method.params.every(param => isRepresentableType(param.type, { returnType: false }));
}

function isRepresentableType(type, { returnType }) {
  const normalized = normalizeType(type);
  if (SKIPPED_TYPES.some(skip => normalized.includes(skip))) return false;
  if (normalized.includes('SGPath')) return !returnType;
  return cppTypeToTs(normalized) !== 'unknown';
}

function cppTypeToTs(cppType) {
  const normalized = normalizeType(cppType)
    .replace(/^const /, '')
    .replace(/&$/, '');

  if (normalized === 'void') return 'void';
  if (normalized === 'bool') return 'boolean';
  if (normalized === 'std::string') return 'string';
  if (normalized === 'SGPath') return 'string';
  if ([
    'int',
    'unsigned int',
    'long',
    'unsigned long',
    'long long',
    'unsigned long long',
    'float',
    'double',
    'size_t',
  ].includes(normalized)) return 'number';

  return 'unknown';
}

function isLoadModelStringOverload(method) {
  return method.params.length === 2
    && normalizeType(method.params[0].type) === 'const std::string&'
    && normalizeType(method.params[1].type) === 'bool';
}

function safeParamName(name) {
  return name || 'value';
}

function normalizeType(type) {
  return type.replace(/\s+/g, ' ').replace(/\s*&\s*/g, '&').trim();
}
