// Generates C++ embind wrapper code for FGFDMExec.

const PRIMITIVE_TYPES = new Set([
  'void',
  'bool',
  'int',
  'unsigned int',
  'double',
  'float',
  'size_t',
  'std::string',
  'const std::string&',
]);

const INTERNAL_ONLY = new Set([
  'BuildPropertyCatalog',
  'GetTemplateFunc',
  'AddTemplateFunc',
  'GetRandomGenerator',
  'SRand',
  'Initialize',
]);

const RUNTIME_REQUIRED = new Set([
  'Run',
  'RunIC',
  'LoadModel',
  'LoadScript',
  'SetRootDir',
  'SetAircraftPath',
  'SetEnginePath',
  'SetSystemsPath',
  'SetOutputPath',
  'GetPropertyValue',
  'SetPropertyValue',
  'QueryPropertyCatalog',
  'GetSimTime',
  'GetDeltaT',
  'SuspendIntegration',
  'ResumeIntegration',
  'Hold',
  'ResetToInitialConditions',
]);

/**
 * @param {{name:string, returnType:string, params:{name:string,type:string}[], isConst?:boolean}[]} methods
 * @returns {string}
 */
export function renderCppBindings(methods) {
  const selected = selectBindableMethods(methods);
  const wrappers = [];
  const bindings = [];

  for (const method of selected) {
    const wrapper = renderWrapper(method);
    if (wrapper) wrappers.push(wrapper.code);
    bindings.push(renderBinding(method, wrapper?.name));
  }

  return `// Auto-generated by scripts/bindings-generator.
// Do not edit manually.

#include <emscripten/bind.h>
#include "FGFDMExec.h"
#include "simgear/misc/sg_path.hxx"

using namespace emscripten;
using namespace JSBSim;

${wrappers.join('\n\n')}

EMSCRIPTEN_BINDINGS(JSBSim) {
  class_<FGFDMExec>("FGFDMExec")
    .constructor()
${bindings.map(line => `    ${line}`).join('\n')}
    ;
}
`;
}

function selectBindableMethods(methods) {
  const byName = groupByName(methods);
  const selected = [];
  const seen = new Set();

  for (const method of methods) {
    if (!isBindable(method)) continue;
    if (method.name === 'QueryPropertyCatalog' && method.params.length !== 2) continue;
    if (method.name === 'LoadModel' && !isLoadModelStringOverload(method)) continue;
    if (byName.get(method.name)?.length > 1 && method.name !== 'LoadModel') continue;

    const key = signatureKey(method);
    if (seen.has(key)) continue;
    seen.add(key);
    selected.push(method);
  }

  const names = new Set(selected.map(method => method.name));
  const missing = [...RUNTIME_REQUIRED].filter(name => !names.has(name));
  if (missing.length > 0) {
    throw new Error(`Generated bindings are missing required methods: ${missing.join(', ')}`);
  }

  return selected.sort((a, b) => {
    const ai = RUNTIME_REQUIRED.has(a.name) ? 0 : 1;
    const bi = RUNTIME_REQUIRED.has(b.name) ? 0 : 1;
    return ai - bi || a.name.localeCompare(b.name);
  });
}

function isBindable(method) {
  if (INTERNAL_ONLY.has(method.name)) return false;
  if (method.isPureVirtual) return false;
  if (!isSupportedType(method.returnType, { returnType: true })) return false;
  return method.params.every(param => isSupportedType(param.type, { returnType: false }));
}

function isSupportedType(type, { returnType }) {
  const normalized = normalizeType(type);
  if (normalized.includes('*')) return false;
  if (normalized.includes('std::shared_ptr')) return false;
  if (normalized.includes('std::vector')) return false;
  if (normalized === 'auto') return false;
  if (normalized.includes('FGTemplateFunc')) return false;
  if (normalized.includes('Element')) return false;
  if (normalized.includes('PropertyCatalogStructure')) return false;
  if (normalized.includes('SGPath')) return !returnType;
  return PRIMITIVE_TYPES.has(normalized);
}

function renderWrapper(method) {
  if (method.name === 'QueryPropertyCatalog') {
    return {
      name: 'QueryPropertyCatalogWrapper',
      code: `static std::string QueryPropertyCatalogWrapper(FGFDMExec& self, const std::string& check) {
  return self.QueryPropertyCatalog(check);
}`,
    };
  }

  if (method.name === 'ResetToInitialConditions') {
    return {
      name: 'ResetToInitialConditionsWrapper',
      code: `static void ResetToInitialConditionsWrapper(FGFDMExec& self) {
  self.ResetToInitialConditions(0);
}`,
    };
  }

  if (!method.params.some(param => normalizeType(param.type).includes('SGPath'))) return null;

  const wrapperName = `${method.name}Wrapper`;
  const params = method.params.map(param => `${wrapperParamType(param.type)} ${param.name}`).join(', ');
  const args = method.params.map(param => {
    return normalizeType(param.type).includes('SGPath') ? `SGPath(${param.name})` : param.name;
  }).join(', ');
  const returnPrefix = normalizeType(method.returnType) === 'void' ? '' : 'return ';

  return {
    name: wrapperName,
    code: `static ${normalizeType(method.returnType)} ${wrapperName}(FGFDMExec& self${params ? `, ${params}` : ''}) {
  ${returnPrefix}self.${method.name}(${args});
}`,
  };
}

function renderBinding(method, wrapperName) {
  const jsName = method.name;
  if (wrapperName) return `.function("${jsName}", &${wrapperName})`;
  if (method.name === 'LoadModel') {
    return `.function("LoadModel", select_overload<bool(const std::string&, bool)>(&FGFDMExec::LoadModel))`;
  }
  return `.function("${jsName}", &FGFDMExec::${method.name})`;
}

function wrapperParamType(type) {
  const normalized = normalizeType(type);
  if (normalized.includes('SGPath')) return 'const std::string&';
  return normalized;
}

function isLoadModelStringOverload(method) {
  return method.params.length === 2
    && normalizeType(method.params[0].type) === 'const std::string&'
    && normalizeType(method.params[1].type) === 'bool';
}

function groupByName(methods) {
  const grouped = new Map();
  for (const method of methods) {
    const list = grouped.get(method.name) ?? [];
    list.push(method);
    grouped.set(method.name, list);
  }
  return grouped;
}

function signatureKey(method) {
  return `${method.name}(${method.params.map(param => normalizeType(param.type)).join(',')})`;
}

function normalizeType(type) {
  return type.replace(/\s+/g, ' ').replace(/\s*&\s*/g, '&').trim();
}
